baseurl = "https://joern.io"
metaDataFormat = "yaml"
title = "Joern - The Bug Hunter's Workbench"
theme = "blist"

## Menu Items
[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url  = "/blog"
  weight = 2
  

  [[menu.main]]
  name = "Community"
  url = "https://discord.com/invite/vv4MH284Hc"
  weight = 3

  
